// 站点配置 schema（P0，拆 7 组）
import type { ConfigDomainSchema } from "./types";

export const siteSchema: ConfigDomainSchema = {
	domain: "site",
	label: "站点",
	group: "站点",
	hasForm: true,
	groups: [
		{
			label: "基础信息",
			fields: [
				{
					key: "title",
					label: "站点标题",
					control: "input",
					placeholder: "如 Firefly",
					help: "浏览器标题栏与 SEO 用",
				},
				{
					key: "subtitle",
					label: "副标题",
					control: "input",
					placeholder: "一句话介绍站点",
				},
				{
					key: "site_url",
					label: "站点 URL",
					control: "input",
					help: "完整站点地址，含协议，无末尾斜杠",
					placeholder: "https://example.com",
					danger: "修改站点 URL 会影响 SEO、RSS、sitemap 与分享链接",
				},
				{
					key: "description",
					label: "站点描述",
					control: "textarea",
					placeholder: "用于搜索引擎摘要的简介",
					rows: 3,
					help: "SEO meta description",
				},
				{
					key: "keywords",
					label: "关键词",
					control: "tags",
					placeholder: "输入关键词后点「添加」",
					help: "SEO keywords，点「添加」写入",
				},
				{
					key: "lang",
					label: "站点语言",
					control: "select",
					options: [
						{ label: "简体中文", value: "zh_CN" },
						{ label: "English", value: "en" },
					],
					danger: "修改语言会切换全站 UI 文案与日期格式",
				},
				{
					key: "timezone",
					label: "时区",
					control: "input",
					placeholder: "Asia/Shanghai",
				},
				{
					key: "siteStartDate",
					label: "建站日期",
					control: "input",
					placeholder: "YYYY-MM-DD",
					help: "页脚运行天数等用",
				},
			],
		},
		{
			label: "主题外观",
			fields: [
				{
					key: "themeColor.hue",
					label: "主题色相 (Hue)",
					control: "slider",
					min: 0,
					max: 360,
					step: 1,
					help: "0–360，对应 HSL 色相",
				},
				{
					key: "themeColor.fixed",
					label: "固定主题色",
					control: "switch",
					help: "开启后访客无法在前台切换色相",
				},
				{
					key: "themeColor.defaultMode",
					label: "默认明暗模式",
					control: "select",
					options: [
						{ label: "跟随系统", value: "system" },
						{ label: "浅色", value: "light" },
						{ label: "深色", value: "dark" },
					],
				},
				{
					key: "pageWidth",
					label: "内容区宽度 (rem)",
					control: "number",
					min: 40,
					max: 200,
					step: 1,
					help: "主内容区最大宽度，单位 rem",
				},
				{
					key: "card.border",
					label: "卡片边框",
					control: "switch",
				},
				{
					key: "card.followTheme",
					label: "卡片跟随主题色",
					control: "switch",
				},
			],
		},
		{
			label: "导航栏",
			fields: [
				{
					key: "navbar.logo.type",
					label: "Logo 类型",
					control: "select",
					options: [
						{ label: "图标库", value: "icon" },
						{ label: "本地图片", value: "image" },
						{ label: "网络图片", value: "url" },
					],
				},
				{
					key: "navbar.logo.value",
					label: "Logo 值",
					control: "input",
					placeholder: "图标名 / 路径 / URL",
					help: "icon 名 / 本地路径 / 网络 URL",
				},
				{
					key: "navbar.logo.alt",
					label: "Logo 替代文本",
					control: "input",
					placeholder: "图片读屏用文字",
				},
				{
					key: "navbar.title",
					label: "导航栏标题",
					control: "input",
					placeholder: "留空用站点标题",
					help: "留空则使用站点标题",
				},
				{
					key: "navbar.widthFull",
					label: "导航栏通栏",
					control: "switch",
				},
				{
					key: "navbar.menuAlign",
					label: "菜单对齐",
					control: "select",
					options: [
						{ label: "居左", value: "left" },
						{ label: "居中", value: "center" },
					],
				},
				{
					key: "navbar.followTheme",
					label: "图标标题跟随主题色",
					control: "switch",
				},
				{
					key: "navbar.stickyNavbar",
					label: "导航栏吸顶",
					control: "switch",
				},
				{
					key: "favicon",
					label: "Favicon 列表",
					control: "objectList",
					itemLabelKey: "src",
					emptyItem: { src: "" },
					itemSchema: [
						{
							key: "src",
							label: "路径",
							control: "input",
							placeholder: "/favicon.ico",
						},
						{
							key: "theme",
							label: "主题",
							control: "input",
							placeholder: "light / dark（可选）",
						},
						{
							key: "sizes",
							label: "尺寸",
							control: "input",
							placeholder: "如 32x32",
						},
					],
					help: "站点图标列表，可配置多套",
				},
			],
		},
		{
			label: "页面开关",
			help: "关闭后该页返回 404，导航栏对应项消失，sitemap 也会排除（部分页面）。",
			fields: [
				{
					key: "pages.friends",
					label: "友链页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.guestbook",
					label: "留言板",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.anime",
					label: "追番页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.gallery",
					label: "相册页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.diary",
					label: "日记页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.dynamic",
					label: "动态页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.projects",
					label: "项目页",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
				{
					key: "pages.timeline",
					label: "时间线",
					control: "switch",
					danger: "关闭页面后该路由返回 404，导航栏项消失",
				},
			],
		},
		{
			label: "文章列表",
			fields: [
				{
					key: "postListLayout.defaultMode",
					label: "桌面默认布局",
					control: "select",
					options: [
						{ label: "列表", value: "list" },
						{ label: "网格", value: "grid" },
					],
				},
				{
					key: "postListLayout.mobileDefaultMode",
					label: "移动端默认布局",
					control: "select",
					options: [
						{ label: "列表", value: "list" },
						{ label: "网格", value: "grid" },
					],
				},
				{
					key: "postListLayout.descriptionLines",
					label: "摘要行数",
					control: "number",
					min: 0,
					max: 10,
				},
				{
					key: "postListLayout.allowSwitch",
					label: "允许切换布局",
					control: "switch",
				},
				{
					key: "postListLayout.allowCoverSwitch",
					label: "允许切换封面显示",
					control: "switch",
				},
				{
					key: "postListLayout.showCover",
					label: "显示封面",
					control: "switch",
				},
				{
					key: "postListLayout.showStatsIcons",
					label: "显示统计图标",
					control: "switch",
				},
				{
					key: "postListLayout.tagsPosition",
					label: "标签位置",
					control: "select",
					options: [
						{ label: "元信息区", value: "meta" },
						{ label: "底部", value: "bottom" },
					],
				},
				{
					key: "postListLayout.meta.showPublished",
					label: "元信息·发布时间",
					control: "switch",
				},
				{
					key: "postListLayout.meta.showCategory",
					label: "元信息·分类",
					control: "switch",
				},
				{
					key: "postListLayout.meta.showTags",
					label: "元信息·标签",
					control: "switch",
				},
				{
					key: "postListLayout.meta.tagCount",
					label: "元信息·标签数量",
					control: "number",
					min: 0,
					max: 20,
				},
				{
					key: "postListLayout.meta.showWords",
					label: "元信息·字数",
					control: "switch",
				},
				{
					key: "postListLayout.meta.showReadingTime",
					label: "元信息·阅读时间",
					control: "switch",
				},
				{
					key: "postListLayout.stats.showPublished",
					label: "统计·发布时间",
					control: "switch",
				},
				{
					key: "postListLayout.stats.showWords",
					label: "统计·字数",
					control: "switch",
				},
				{
					key: "postListLayout.stats.showReadingTime",
					label: "统计·阅读时间",
					control: "switch",
				},
				{
					key: "postListLayout.grid.masonry",
					label: "网格瀑布流",
					control: "switch",
				},
				{
					key: "postListLayout.grid.columnWidth",
					label: "网格列宽 (px)",
					control: "number",
					min: 200,
					max: 600,
				},
				{
					key: "pagination.postsPerPage",
					label: "每页文章数",
					control: "number",
					min: 1,
					max: 100,
					help: "首页分页 pageSize",
				},
				{
					key: "categoryBar",
					label: "分类栏",
					control: "switch",
				},
				{
					key: "foldArticle",
					label: "归档默认折叠非首年",
					control: "switch",
				},
			],
		},
		{
			label: "统计分析",
			fields: [
				{
					key: "analytics.googleAnalyticsId",
					label: "Google Analytics ID",
					control: "input",
					placeholder: "G-XXXXXXXX",
				},
				{
					key: "analytics.microsoftClarityId",
					label: "Microsoft Clarity ID",
					control: "input",
					placeholder: "控制台里的项目 ID",
				},
				{
					key: "analytics.umamiAnalytics.websiteId",
					label: "Umami Website ID",
					control: "input",
					placeholder: "Umami 站点 UUID",
				},
				{
					key: "analytics.umamiAnalytics.shareUrl",
					label: "Umami 分享链接",
					control: "input",
					placeholder: "https://…/share/…",
				},
				{
					key: "analytics.umamiAnalytics.scriptUrl",
					label: "Umami 脚本地址",
					control: "input",
					placeholder: "https://…/script.js",
				},
				{
					key: "analytics.umamiAnalytics.trackOutboundLinks",
					label: "Umami 追踪外链",
					control: "switch",
				},
				{
					key: "analytics.umamiAnalytics.collectWebVitals",
					label: "Umami Web Vitals",
					control: "switch",
				},
				{
					key: "analytics.umamiAnalytics.replays.enabled",
					label: "Umami 会话回放",
					control: "switch",
				},
				{
					key: "analytics.la51Analytics.Id",
					label: "51.la ID",
					control: "input",
					placeholder: "51.la 站点 ID",
				},
				{
					key: "analytics.la51Analytics.sdkUrl",
					label: "51.la SDK URL",
					control: "input",
					placeholder: "https://…/js/…js",
				},
				{
					key: "analytics.la51Analytics.ck",
					label: "51.la ck",
					control: "input",
					placeholder: "控制台提供的 ck",
				},
				{
					key: "analytics.la51Analytics.autoTrack",
					label: "51.la 自动追踪",
					control: "switch",
				},
				{
					key: "analytics.la51Analytics.hashMode",
					label: "51.la Hash 模式",
					control: "switch",
				},
				{
					key: "analytics.la51Analytics.screenRecord",
					label: "51.la 屏幕录制",
					control: "switch",
				},
			],
		},
		{
			label: "功能开关",
			fields: [
				{
					key: "showLastModified",
					label: "显示上次编辑卡片",
					control: "switch",
				},
				{
					key: "outdatedThreshold",
					label: "过期阈值（天）",
					control: "number",
					min: 0,
					help: "超过此天数才显示上次编辑提示",
				},
				{
					key: "sharePoster",
					label: "分享海报",
					control: "switch",
				},
				{
					key: "generateOgImages",
					label: "生成 OG 图片",
					control: "switch",
				},
				{
					key: "aiSummary.enable",
					label: "AI 摘要展示",
					control: "switch",
					help: "仅控制文章页是否展示摘要卡片；摘要本身由本地脚本预生成",
				},
				{
					key: "anime.bilibili.uid",
					label: "Bilibili UID",
					control: "input",
					placeholder: "B站用户数字 UID",
					help: "追番页数据源；留空且无 TMDB 时显示未配置",
				},
				{
					key: "anime.tmdb.apiKey",
					label: "TMDB API Key",
					control: "input",
					placeholder: "可选，TMDB API Key",
				},
				{
					key: "anime.tmdb.listId",
					label: "TMDB List ID",
					control: "input",
					placeholder: "可选，TMDB 列表 ID",
				},
				{
					key: "diary.defaultAvatar",
					label: "日记默认头像",
					control: "imageUrl",
					placeholder: "头像路径或 URL",
				},
				{
					key: "rehypeCallouts.theme",
					label: "Callouts 主题",
					control: "input",
					placeholder: "如 github",
					help: "rehype-callouts 主题名，如 github",
				},
				{
					key: "rehypeCallouts.enablePythonMarkdownAdmonitions",
					label: "兼容 Python Admonition",
					control: "switch",
					help: "开启后支持 !!! note 这类 Python-Markdown 语法",
				},
				{
					key: "imageOptimization.formats",
					label: "图片优化格式",
					control: "select",
					options: [
						{ label: "AVIF", value: "avif" },
						{ label: "WebP", value: "webp" },
						{ label: "两者", value: "both" },
					],
					danger: "修改图片优化格式会影响构建产物体积与兼容性",
				},
				{
					key: "imageOptimization.quality",
					label: "图片质量",
					control: "slider",
					min: 1,
					max: 100,
					step: 1,
				},
				{
					key: "imageOptimization.noReferrerDomains",
					label: "无 Referrer 域名",
					control: "tags",
					placeholder: "如 i.imgur.com",
					help: "对这些域名的图片请求不加 Referer",
				},
			],
		},
	],
};
